In [1]:
import numpy as np
from prediction import *
from gridworld import *

In [2]:
env = GridWorld((4,4), 0.9)

In [3]:
print(env.get_actions(1))
print(env.get_terminal_states())
print(env.get_random_actions([0,1,2,3]))
print(env.get_states())
print(env.reward(0, -1))
print(env.get_probability(7, -1, 3, 4))

[-4, -1, 1, 4]
[0, 15]
[-4  1  1 -4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
-1
1.0


In [4]:
states = env.get_states()
policy = [0] * len(states)
for s in states:
    actions = env.get_actions(s)
#     action = actions[np.random.randint(len(actions))]
    action = actions[0]
    policy[s] = action
print(policy)

[-4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4]


In [5]:
ipe = IterativePolicyEvaluation(env)
print(ipe.run(policy))

D  1.0
D  0.8999999999999999
D  0.81
D  0.7290000000000001
D  0.6561000000000003
D  0.59049
D  0.531441
D  0.47829690000000014
D  0.43046720999999977
D  0.38742048900000015
D  0.3486784401000005
D  0.3138105960899997
D  0.28242953648099967
D  0.25418658283289997
D  0.2287679245496097
D  0.20589113209465015
D  0.18530201888518505
D  0.16677181699666477
D  0.1500946352969983
D  0.13508517176729917
D  0.12157665459056943
D  0.10941898913151249
D  0.0984770902183616
D  0.08862938119652597
D  0.0797664430768723
D  0.0717897987691849
D  0.06461081889226605
D  0.05814973700304016
D  0.052334763302736675
D  0.047101286972463186
D  0.042391158275215446
D  0.03815204244769532
D  0.034336838202925435
D  0.030903154382633247
D  0.027812838944369034
D  0.025031555049931598
D  0.022528399544938793
D  0.020275559590444914
D  0.018248003631400778
D  0.016423203268260522
D  0.014780882941435536
D  0.01330279464729145
D  0.011972515182561594
D  0.010775263664305257
D  0.009697737297875264
D  0.008727963

In [6]:
ipe.v

array([ 0.       , -9.9999991, -9.9999991, -9.9999991, -1.       ,
       -9.9999991, -9.9999991, -9.9999991, -1.9      , -9.9999991,
       -9.9999991, -9.9999991, -2.71     , -9.9999991, -9.9999991,
        0.       ])

In [7]:
t = PolicyIteration(env)
t.run()

D  1.0
D  0.8999999999999999
D  0.81
D  0.7290000000000001
D  0.6561000000000003
D  0.59049
D  0.531441
D  0.47829690000000014
D  0.43046720999999977
D  0.38742048900000015
D  0.3486784401000005
D  0.3138105960899997
D  0.28242953648099967
D  0.25418658283289997
D  0.2287679245496097
D  0.20589113209465015
D  0.18530201888518505
D  0.16677181699666477
D  0.1500946352969983
D  0.13508517176729917
D  0.12157665459056943
D  0.10941898913151249
D  0.0984770902183616
D  0.08862938119652597
D  0.0797664430768723
D  0.0717897987691849
D  0.06461081889226605
D  0.05814973700304016
D  0.052334763302736675
D  0.047101286972463186
D  0.042391158275215446
D  0.03815204244769532
D  0.034336838202925435
D  0.030903154382633247
D  0.027812838944369034
D  0.025031555049931598
D  0.022528399544938793
D  0.020275559590444914
D  0.018248003631400778
D  0.016423203268260522
D  0.014780882941435536
D  0.01330279464729145
D  0.011972515182561594
D  0.010775263664305257
D  0.009697737297875264
D  0.008727963

(array([-4, -1, -1, -1, -4, -4, -4,  4,  4, -1,  1,  4,  4, -1,  1,  1]),
 array([ 0.  , -1.  , -1.9 , -2.71, -1.  , -1.9 , -2.71, -1.9 , -1.  ,
        -1.9 , -1.9 , -1.  ,  0.  , -1.  , -1.  ,  0.  ]))